{{-- Star Federation archive — raw Datastar + Rocket + Stellar.
     Standalone page: Stellar styles bare elements, so this view owns its whole
     <head> instead of using the app layout.
     Note: @@get is the Blade escape for a literal @get. --}}
<!doctype html>
<!-- THEME: seeded from the OS (data-match-media), overridden by the button,
     remembered across visits (data-persist) — all Datastar Pro attributes. -->
<html lang="en" data-signals="{query: '', _aloft: false, _sky: 0, _theme: ''}"
      data-match-media:_prefersdark="(prefers-color-scheme: dark)"
      data-persist:notacult="{include: /^_theme$/}"
      data-computed:_dark="$_theme ? $_theme === 'dark' : $_prefersdark"
      data-class:dark="$_dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Not a Space Cult — the archive</title>
<link rel="icon" href="/datastar/pro/rocket.png">
<link rel="stylesheet" href="/datastar/pro/stellar.css">   {{-- generated by `stellar gen` --}}
<link rel="stylesheet" href="/datastar/pro/app.css">       {{-- the only css we author --}}
@verbatim
<script type="module">
import { rocket } from '/datastar/pro/datastar-pro.js'

// ROCKET: the server writes <yt-clip video start>; this makes it a real
// component with typed props and its own private state.
rocket('yt-clip', {
  mode: 'light',
  props: ({ string, number }) => ({
    video: string,
    start: number.min(0),
  }),
  setup: ({ $$ }) => { $$.playing = false },
  render: ({ html, props: { video, start } }) => html`
    <button class="btn" data-show="!$$playing"
            data-on:click="@setAll(false, {include: /\.playing$/}); $$playing = true">&#9654; Watch</button>
    <template data-if="$$playing">
      <iframe src="https://www.youtube-nocookie.com/embed/${video}?start=${start}&autoplay=1"
              title="YouTube player" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </template>`,
})
</script>
@endverbatim
</head>
<body>
  <!-- one signal drives the class on <html>; Stellar does the rest -->
  <button class="theme" aria-label="Switch theme"
          data-on:click="$_theme = $_dark ? 'light' : 'dark'">
    <svg data-show="!$_dark" width="21" height="21" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="1.7" stroke-linejoin="round">
      <path d="M20 14.5A8.5 8.5 0 0 1 9.5 4a8.5 8.5 0 1 0 10.5 10.5z"/>
    </svg>
    <svg data-show="$_dark" width="21" height="21" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="1.7" stroke-linecap="round">
      <circle cx="12" cy="12" r="4.1"/>
      <path d="M12 2.4v2.2M12 19.4v2.2M2.4 12h2.2M19.4 12h2.2M5.2 5.2l1.6 1.6M17.2 17.2l1.6 1.6M18.8 5.2l-1.6 1.6M6.8 17.2l-1.6 1.6"/>
    </svg>
  </button>
{{-- column-reverse: the first child renders at the BOTTOM, and the scroller
     opens there — so the page simply starts on the planet. No scrolling. --}}
{{-- DATASTAR: a column-reverse scroller runs scrollTop NEGATIVE as you go up,
     so leaving the ground is simply scrollTop < 0. One signal, no custom JS. --}}
<div class="sky" aria-hidden="true"
     data-style:transform="`translate3d(0, ${$_sky % 1400}px, 0)`"></div>

<div class="page"
     data-on:scroll__throttle.16ms.trailing="$_aloft = evt.target.scrollTop < -40;
                                             $_sky = evt.target.scrollTop * -0.35"
>

  {{-- The rocket. Sticky, not fixed: it rests on the pad at the bottom of the
       scroller and rides at that same height as you climb away. --}}
  <div class="flight" aria-hidden="true">
    {{-- one signal picks the picture: engine off on the pad, lit once climbing --}}
    <img class="rocket" src="/datastar/pro/rocket-landed.png" alt="" width="512" height="512"
         data-attr:src="$_aloft ? '/datastar/pro/rocket.png' : '/datastar/pro/rocket-landed.png'">
  </div>

  {{-- the planet: title, description and the search live on its surface --}}
  <div class="ground">
    <div class="planet" aria-hidden="true"></div>

    {{-- where the timeline touches down --}}
    <div class="landing" aria-hidden="true"><div class="target"></div></div>

    <div class="pad">
      <h1>Not a Space Cult</h1>
      <p class="lede">Every word of 26 episodes. Search, then look up to the stars.</p>

      {{-- DATASTAR: signals go up, rendered HTML comes back down over SSE --}}
      <input type="search" placeholder="Search the transcripts&hellip;"
             data-bind:query
             data-on:input__debounce.300ms="@@get('/datastar/pro/search')">
    </div>
  </div>

  {{-- suggestions float above the planet, split so the timeline falls between them --}}
  @php $half = intdiv(count($terms), 2); @endphp
  <nav class="chips">
    <div class="chip-side">
      <button class="chip" data-on:click="$query = ''; @@get('/datastar/pro/search')">all</button>
      @foreach (array_slice($terms, 0, $half) as $term)
        <button class="chip" data-term="{{ $term->word }}"
                data-on:click="$query = '{{ $term->word }}'; @@get('/datastar/pro/search')">{{ $term->word }} <small>{{ $term->hits }}</small></button>
      @endforeach
    </div>
    <div class="chip-side">
      @foreach (array_slice($terms, $half) as $term)
        <button class="chip" data-term="{{ $term->word }}"
                data-on:click="$query = '{{ $term->word }}'; @@get('/datastar/pro/search')">{{ $term->word }} <small>{{ $term->hits }}</small></button>
      @endforeach
    </div>
  </nav>

  <main id="results" data-init="@@get('/datastar/pro/search')">&hellip;</main>

</div>
</body>
</html>
